version: '3'

services:
#   rabbitmq:
#     image: rabbitmq:3-management
#     container_name: rabbitmq
#     ports:
#       - 5672:5672
#       - 15672:15672
#     environment:
#       RABBITMQ_DEFAULT_USER: guest
#       RABBITMQ_DEFAULT_PASS: guest
#       RABBITMQ_DEFAULT_VHOST: /
#     healthcheck:
#       test: ["CMD", "rabbitmq-diagnostics", "ping"]
#       interval: 5s
#       timeout: 5s
#       retries: 2
#     networks:
#       - master-go-expert-networks

  exchange-rate-api:
    image: fabiocaffarello/exchange-rate-api:latest
    container_name: exchange-rate-api
    ports:
      - 8080:8000
    networks:
      - nx-events-lake-network

networks:
  master-go-expert-networks:
    name: master-go-expert-network
    driver: bridge
